// predefinedPlayers.js
export const predefinedPlayers = {
  goalkeepers: [
    {
      name: "Neuer",
      preferredPosition: "GK",
      secondaryPositions: [],
      overallRating: 92,
      pace: 60,
      dribbling: 65,
      passing: 70,
      shooting: 50,
      defending: 55,
      physical: 80,
      goalkeeping: 92,
      imageUrl: "/images/neuer.jpg",
      team: "Bayern Munich",
      nationality: "Germany",
      age: 38,
    },
    {
      name: "Buffon",
      preferredPosition: "GK",
      secondaryPositions: [],
      overallRating: 90,
      pace: 58,
      dribbling: 60,
      passing: 68,
      shooting: 48,
      defending: 53,
      physical: 78,
      goalkeeping: 90,
      imageUrl: "/images/buffon.jpg",
      team: "Juventus",
      nationality: "Italy",
      age: 46,
    },
    {
      name: "Casillas",
      preferredPosition: "GK",
      secondaryPositions: [],
      overallRating: 89,
      pace: 62,
      dribbling: 63,
      passing: 69,
      shooting: 49,
      defending: 54,
      physical: 79,
      goalkeeping: 89,
      imageUrl: "/images/casillas.jpg",
      team: "Real Madrid",
      nationality: "Spain",
      age: 43,
    },
    {
      name: "Ter Stegen",
      preferredPosition: "GK",
      secondaryPositions: [],
      overallRating: 91,
      pace: 61,
      dribbling: 66,
      passing: 72,
      shooting: 51,
      defending: 56,
      physical: 81,
      goalkeeping: 91,
      imageUrl: "/images/terstegen.jpg",
      team: "Barcelona",
      nationality: "Germany",
      age: 32,
    },
  ],
  defenders: [
    {
      name: "Alba",
      preferredPosition: "LB",
      secondaryPositions: ["LWB"],
      overallRating: 86,
      pace: 88,
      dribbling: 80,
      passing: 82,
      shooting: 65,
      defending: 84,
      physical: 75,
      goalkeeping: 0,
      imageUrl: "/images/alba.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 35,
    },
    {
      name: "Maldini",
      preferredPosition: "LB",
      secondaryPositions: ["CB"],
      overallRating: 94,
      pace: 80,
      dribbling: 75,
      passing: 78,
      shooting: 60,
      defending: 95,
      physical: 90,
      goalkeeping: 0,
      imageUrl: "/images/maldini.jpg",
      team: "AC Milan",
      nationality: "Italy",
      age: 56,
    },
    {
      name: "Marcelo",
      preferredPosition: "LB",
      secondaryPositions: ["LWB", "LM"],
      overallRating: 85,
      pace: 85,
      dribbling: 88,
      passing: 87,
      shooting: 70,
      defending: 78,
      physical: 70,
      goalkeeping: 0,
      imageUrl: "/images/marcelo.jpg",
      team: "Real Madrid",
      nationality: "Brazil",
      age: 36,
    },
    {
      name: "Cancelo",
      preferredPosition: "LB",
      secondaryPositions: ["RB", "CM"],
      overallRating: 87,
      pace: 86,
      dribbling: 89,
      passing: 88,
      shooting: 72,
      defending: 80,
      physical: 78,
      goalkeeping: 0,
      imageUrl: "/images/cancelo.jpg",
      team: "Manchester City",
      nationality: "Portugal",
      age: 30,
    },
    {
      name: "Araujo",
      preferredPosition: "CB",
      secondaryPositions: ["RB"],
      overallRating: 87,
      pace: 82,
      dribbling: 70,
      passing: 70,
      shooting: 55,
      defending: 88,
      physical: 90,
      goalkeeping: 0,
      imageUrl: "/images/araujo.jpg",
      team: "Barcelona",
      nationality: "Uruguay",
      age: 25,
    },
    {
      name: "Van Dijk",
      preferredPosition: "CB",
      secondaryPositions: [],
      overallRating: 91,
      pace: 78,
      dribbling: 70,
      passing: 75,
      shooting: 60,
      defending: 92,
      physical: 93,
      goalkeeping: 0,
      imageUrl: "/images/vandijk.jpg",
      team: "Liverpool",
      nationality: "Netherlands",
      age: 33,
    },
    {
      name: "Ramos",
      preferredPosition: "CB",
      secondaryPositions: ["RB"],
      overallRating: 90,
      pace: 75,
      dribbling: 70,
      passing: 72,
      shooting: 68,
      defending: 91,
      physical: 92,
      goalkeeping: 0,
      imageUrl: "/images/ramos.jpg",
      team: "Paris Saint-Germain",
      nationality: "Spain",
      age: 38,
    },
    {
      name: "Pique",
      preferredPosition: "CB",
      secondaryPositions: [],
      overallRating: 88,
      pace: 70,
      dribbling: 68,
      passing: 70,
      shooting: 58,
      defending: 89,
      physical: 88,
      goalkeeping: 0,
      imageUrl: "/images/pique.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 37,
    },
    {
      name: "Kounde",
      preferredPosition: "RB",
      secondaryPositions: ["CB"],
      overallRating: 86,
      pace: 85,
      dribbling: 80,
      passing: 78,
      shooting: 60,
      defending: 85,
      physical: 82,
      goalkeeping: 0,
      imageUrl: "/images/kounde.jpg",
      team: "Barcelona",
      nationality: "France",
      age: 25,
    },
    {
      name: "Alves",
      preferredPosition: "RB",
      secondaryPositions: [],
      overallRating: 84,
      pace: 83,
      dribbling: 85,
      passing: 86,
      shooting: 68,
      defending: 78,
      physical: 75,
      goalkeeping: 0,
      imageUrl: "/images/alves.jpg",
      team: "São Paulo",
      nationality: "Brazil",
      age: 41,
    },
    {
      name: "Carvajal",
      preferredPosition: "RB",
      secondaryPositions: [],
      overallRating: 83,
      pace: 80,
      dribbling: 78,
      passing: 79,
      shooting: 65,
      defending: 82,
      physical: 78,
      goalkeeping: 0,
      imageUrl: "/images/carvajal.jpg",
      team: "Real Madrid",
      nationality: "Spain",
      age: 32,
    },
    {
      name: "Trent",
      preferredPosition: "RB",
      secondaryPositions: ["CM", "RW"],
      overallRating: 87,
      pace: 80,
      dribbling: 85,
      passing: 90,
      shooting: 75,
      defending: 78,
      physical: 78,
      goalkeeping: 0,
      imageUrl: "/images/trent.jpg",
      team: "Liverpool",
      nationality: "England",
      age: 25,
    },
  ],
  midfielders: [
    {
      name: "Zidane",
      preferredPosition: "CAM",
      secondaryPositions: ["CM"],
      overallRating: 94,
      pace: 75,
      dribbling: 95,
      passing: 92,
      shooting: 85,
      defending: 60,
      physical: 80,
      goalkeeping: 0,
      imageUrl: "/images/zidane.jpg",
      team: "Real Madrid",
      nationality: "France",
      age: 52,
    },
    {
      name: "Maradona",
      preferredPosition: "CAM",
      secondaryPositions: ["LW", "RW"],
      overallRating: 95,
      pace: 80,
      dribbling: 98,
      passing: 90,
      shooting: 88,
      defending: 55,
      physical: 70,
      goalkeeping: 0,
      imageUrl: "/images/maradona.jpg",
      team: "Napoli",
      nationality: "Argentina",
      age: 63,
    },
    {
      name: "De Bruyne",
      preferredPosition: "CAM",
      secondaryPositions: ["CM"],
      overallRating: 93,
      pace: 78,
      dribbling: 88,
      passing: 94,
      shooting: 90,
      defending: 65,
      physical: 80,
      goalkeeping: 0,
      imageUrl: "/images/debruyne.jpg",
      team: "Manchester City",
      nationality: "Belgium",
      age: 33,
    },
    {
      name: "Bellingham",
      preferredPosition: "CAM",
      secondaryPositions: ["CM"],
      overallRating: 89,
      pace: 82,
      dribbling: 85,
      passing: 87,
      shooting: 80,
      defending: 75,
      physical: 88,
      goalkeeping: 0,
      imageUrl: "/images/bellingham.jpg",
      team: "Real Madrid",
      nationality: "England",
      age: 21,
    },
    {
      name: "Iniesta",
      preferredPosition: "CM",
      secondaryPositions: ["CAM"],
      overallRating: 92,
      pace: 70,
      dribbling: 92,
      passing: 95,
      shooting: 70,
      defending: 65,
      physical: 68,
      goalkeeping: 0,
      imageUrl: "/images/iniesta.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 40,
    },
    {
      name: "Xavi",
      preferredPosition: "CM",
      secondaryPositions: ["CDM"],
      overallRating: 91,
      pace: 65,
      dribbling: 88,
      passing: 96,
      shooting: 60,
      defending: 70,
      physical: 65,
      goalkeeping: 0,
      imageUrl: "/images/xavi.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 44,
    },
    {
      name: "Modric",
      preferredPosition: "CM",
      secondaryPositions: ["CAM"],
      overallRating: 90,
      pace: 70,
      dribbling: 90,
      passing: 93,
      shooting: 75,
      defending: 70,
      physical: 70,
      goalkeeping: 0,
      imageUrl: "/images/modric.jpg",
      team: "Real Madrid",
      nationality: "Croatia",
      age: 39,
    },
    {
      name: "Kroos",
      preferredPosition: "CM",
      secondaryPositions: ["CDM"],
      overallRating: 89,
      pace: 60,
      dribbling: 85,
      passing: 94,
      shooting: 80,
      defending: 72,
      physical: 75,
      goalkeeping: 0,
      imageUrl: "/images/kroos.jpg",
      team: "Real Madrid",
      nationality: "Germany",
      age: 34,
    },
    {
      name: "Pedri",
      preferredPosition: "CM",
      secondaryPositions: ["CAM"],
      overallRating: 88,
      pace: 75,
      dribbling: 90,
      passing: 92,
      shooting: 70,
      defending: 70,
      physical: 70,
      goalkeeping: 0,
      imageUrl: "/images/pedri.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 21,
    },
    {
      name: "Valverde",
      preferredPosition: "CDM",
      secondaryPositions: ["CM"],
      overallRating: 87,
      pace: 85,
      dribbling: 80,
      passing: 82,
      shooting: 80,
      defending: 85,
      physical: 88,
      goalkeeping: 0,
      imageUrl: "/images/valverde.jpg",
      team: "Real Madrid",
      nationality: "Uruguay",
      age: 26,
    },
    {
      name: "Rodri",
      preferredPosition: "CDM",
      secondaryPositions: ["CB"],
      overallRating: 89,
      pace: 65,
      dribbling: 75,
      passing: 88,
      shooting: 70,
      defending: 90,
      physical: 90,
      goalkeeping: 0,
      imageUrl: "/images/rodri.jpg",
      team: "Manchester City",
      nationality: "Spain",
      age: 28,
    },
    {
      name: "Busquets",
      preferredPosition: "CDM",
      secondaryPositions: ["CM"],
      overallRating: 88,
      pace: 55,
      dribbling: 80,
      passing: 90,
      shooting: 60,
      defending: 88,
      physical: 80,
      goalkeeping: 0,
      imageUrl: "/images/busquets.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 36,
    },
  ],
  forwards: [
    {
      name: "Messi",
      preferredPosition: "RW",
      secondaryPositions: ["CAM"],
      overallRating: 96,
      pace: 90,
      dribbling: 98,
      passing: 90,
      shooting: 95,
      defending: 35,
      physical: 65,
      goalkeeping: 0,
      imageUrl: "/images/messi.jpg",
      team: "Inter Miami",
      nationality: "Argentina",
      age: 37,
    },
    {
      name: "Salah",
      preferredPosition: "RW",
      secondaryPositions: ["LW"],
      overallRating: 90,
      pace: 90,
      dribbling: 88,
      passing: 80,
      shooting: 90,
      defending: 40,
      physical: 75,
      goalkeeping: 0,
      imageUrl: "/images/salah.jpg",
      team: "Liverpool",
      nationality: "Egypt",
      age: 32,
    },
    {
      name: "Bale",
      preferredPosition: "RW",
      secondaryPositions: ["ST"],
      overallRating: 87,
      pace: 92,
      dribbling: 85,
      passing: 78,
      shooting: 88,
      defending: 30,
      physical: 80,
      goalkeeping: 0,
      imageUrl: "/images/bale.jpg",
      team: "Los Angeles FC",
      nationality: "Wales",
      age: 35,
    },
    {
      name: "Yamal",
      preferredPosition: "RW",
      secondaryPositions: [],
      overallRating: 84,
      pace: 88,
      dribbling: 90,
      passing: 80,
      shooting: 80,
      defending: 30,
      physical: 68,
      goalkeeping: 0,
      imageUrl: "/images/yamal.jpg",
      team: "Barcelona",
      nationality: "Spain",
      age: 17,
    },
    {
      name: "Haaland",
      preferredPosition: "ST",
      secondaryPositions: ["LW"],
      overallRating: 91,
      pace: 90,
      dribbling: 75,
      passing: 70,
      shooting: 95,
      defending: 30,
      physical: 90,
      goalkeeping: 0,
      imageUrl: "/images/haaland.jpg",
      team: "Manchester City",
      nationality: "Norway",
      age: 24,
    },
    {
      name: "Lewandowski",
      preferredPosition: "ST",
      secondaryPositions: [],
      overallRating: 90,
      pace: 80,
      dribbling: 80,
      passing: 75,
      shooting: 93,
      defending: 30,
      physical: 85,
      goalkeeping: 0,
      imageUrl: "/images/lewandowski.jpg",
      team: "Barcelona",
      nationality: "Poland",
      age: 36,
    },
    {
      name: "Benzema",
      preferredPosition: "ST",
      secondaryPositions: ["CAM"],
      overallRating: 89,
      pace: 78,
      dribbling: 85,
      passing: 82,
      shooting: 90,
      defending: 35,
      physical: 80,
      goalkeeping: 0,
      imageUrl: "/images/benzema.jpg",
      team: "Al-Ittihad",
      nationality: "France",
      age: 36,
    },
    {
      name: "Suarez",
      preferredPosition: "ST",
      secondaryPositions: [],
      overallRating: 88,
      pace: 75,
      dribbling: 85,
      passing: 78,
      shooting: 90,
      defending: 40,
      physical: 82,
      goalkeeping: 0,
      imageUrl: "/images/suarez.jpg",
      team: "Inter Miami",
      nationality: "Uruguay",
      age: 37,
    },
    {
      name: "Ronaldo",
      preferredPosition: "LW",
      secondaryPositions: ["ST", "RW"],
      overallRating: 92,
      pace: 88,
      dribbling: 85,
      passing: 78,
      shooting: 95,
      defending: 30,
      physical: 88,
      goalkeeping: 0,
      imageUrl: "/images/ronaldo.jpg",
      team: "Al-Nassr",
      nationality: "Portugal",
      age: 39,
    },
    {
      name: "Neymar",
      preferredPosition: "LW",
      secondaryPositions: ["CAM"],
      overallRating: 91,
      pace: 88,
      dribbling: 95,
      passing: 88,
      shooting: 85,
      defending: 30,
      physical: 70,
      goalkeeping: 0,
      imageUrl: "/images/neymar.jpg",
      team: "Al-Hilal",
      nationality: "Brazil",
      age: 32,
    },
    {
      name: "Ronaldinho",
      preferredPosition: "LW",
      secondaryPositions: ["CAM"],
      overallRating: 93,
      pace: 80,
      dribbling: 96,
      passing: 90,
      shooting: 85,
      defending: 40,
      physical: 75,
      goalkeeping: 0,
      imageUrl: "/images/ronaldinho.jpg",
      team: "Retired",
      nationality: "Brazil",
      age: 44,
    },
    {
      name: "Mbappe",
      preferredPosition: "LW",
      secondaryPositions: ["ST", "RW"],
      overallRating: 94,
      pace: 96,
      dribbling: 90,
      passing: 82,
      shooting: 92,
      defending: 30,
      physical: 78,
      goalkeeping: 0,
      imageUrl: "/images/mbappe.jpg",
      team: "Paris Saint-Germain",
      nationality: "France",
      age: 25,
    },
  ],
};
